version: "3"

tasks:
  run:
    desc: Run the Claude usage monitor
    dir: src
    cmds:
      - uv run --frozen python -m claude_monitor

  update:
    desc: Update repository from upstream
    cmds:
      - git fetch upstream
      - git merge upstream/main
      - git push origin main
